# Configuration vars for cmd/app
[app]
name = "Fiber starter"
port = ":5860"
idle-timeout = 5 # As seconds
print-routes = false
prefork = true
production = false
cors = "http://localhost:3000"

[app.tls]
enable = false
cert-file = "./storage/selfsigned.crt"
key-file = "./storage/selfsigned.key"

[logger]
time-format = "" # https://pkg.go.dev/time#pkg-constants, https://github.com/rs/zerolog/blob/master/api.go#L10 
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[github]
github-uri = "https://github.com/Camilo2102/"
auto-crud-url = "Springboot-kotlin-autogenerable-crud"

[docker]
user = "cammd21"
password = "R7PXqqH2."

[folders]
root-folder = "C://archivos-tesis/"
auto-crud-model-folder = "src//main//kotlin//cloud//webgen//web//core//autogenerablecrudktl//models"
auto-crud-repository-folder = "src//main//kotlin//cloud//webgen//web//core//autogenerablecrudktl//repository"

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true

[middleware.monitor]
enable = false
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = false
max = 20
expiration_seconds = 60

[middleware.jwt]
secret = "secret"
expiration_seconds = 3600

[middleware.filesystem]
enable = false
browse = true
max_age = 3600
index = "index.html"
root = "./storage/public"